<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sliderValue</name>
   <tag></tag>
   <elementGuidId>1ee04842-b8c4-4041-b851-fd9645797d31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sliderValue</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
