<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slider</name>
   <tag></tag>
   <elementGuidId>ba5b9c44-8a8f-4d7a-807c-00bb709bedad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.range-slider.range-slider--primary</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
