<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>daypicker_Select</name>
   <tag></tag>
   <elementGuidId>586a29ca-1ec9-436e-bad7-87db16f3df3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.react-datepicker__day.react-datepicker__day--012</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
