<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gender_Other_Radio</name>
   <tag></tag>
   <elementGuidId>7dadf45b-6351-465e-97d6-644cf5db69d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label[for=&quot;gender-radio-3&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
