<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hobbies_Reading_Check</name>
   <tag></tag>
   <elementGuidId>56c177a2-5b57-4496-979f-40df2e5f42e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label[for=&quot;hobbies-checkbox-2&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
