<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yearpicker_Select</name>
   <tag></tag>
   <elementGuidId>7f8366b5-1025-42f4-b3fc-616a0eff7a8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.react-datepicker__year-select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
