<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dob_Input_Field</name>
   <tag></tag>
   <elementGuidId>05354c28-4e72-47a5-8613-973a93d5f421</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#dateOfBirthInput</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
