<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subjects_Input_Field</name>
   <tag></tag>
   <elementGuidId>81b34278-52e1-4783-97ff-39c60a6d81c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;subjectsContainer&quot;]/div/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input#subjectsInput</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
