<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>homeFNewTab_Link</name>
   <tag></tag>
   <elementGuidId>4d758799-3960-4b47-87f7-0db6ac779ac0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dynamicLink</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
