<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>homeNewTab_Link</name>
   <tag></tag>
   <elementGuidId>b1a18d85-46c2-4c7f-855d-138e3b5d88bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#simpleLink</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
